"""Read-only feature store for manifests generated by OfflineKeyframeEmbedder."""

from __future__ import annotations

import json
import hashlib
import math
from pathlib import Path
from typing import Any, Iterator, Sequence

import numpy as np

from domain.models import KeyframeRecord
from indexing.base import FeatureValidationReport
from indexing.feature_store import FeatureMappingVerificationError, FeatureStoreValidationError


class ShardedNpyFeatureStore:
    def __init__(
        self,
        manifest_path: Path,
        keyframes: Sequence[KeyframeRecord],
        mmap: bool = True,
        validation_batch_size: int = 8192,
    ) -> None:
        if validation_batch_size < 1:
            raise ValueError("validation_batch_size must be at least 1")
        self._manifest_path = manifest_path.resolve()
        self._manifest = self._load_manifest(self._manifest_path)
        self._ordered_uids = tuple(self._manifest["source"]["keyframe_uid_order"])
        self._metadata_by_uid = self._validate_metadata(keyframes)
        self._arrays = self._load_shards(mmap)
        self._validation = self._validate_vectors(validation_batch_size, mmap)

    @property
    def count(self) -> int:
        return len(self._ordered_uids)

    @property
    def dimension(self) -> int:
        return int(self._manifest["embedding_dimension"])

    @property
    def ordered_uids(self) -> tuple[str, ...]:
        return self._ordered_uids

    @property
    def manifest_path(self) -> Path:
        return self._manifest_path

    @property
    def manifest(self) -> dict[str, Any]:
        return self._manifest

    @property
    def validation(self) -> FeatureValidationReport:
        return self._validation

    def metadata_for_id(self, item_id: str) -> KeyframeRecord:
        try:
            return self._metadata_by_uid[item_id]
        except KeyError as error:
            raise KeyError(f"Unknown embedded keyframe UID: {item_id}") from error

    def iter_batches(self, batch_size: int) -> Iterator[tuple[tuple[str, ...], np.ndarray]]:
        if batch_size < 1:
            raise ValueError("batch_size must be at least 1")
        uid_offset = 0
        for array in self._arrays:
            for start in range(0, array.shape[0], batch_size):
                end = min(start + batch_size, array.shape[0])
                yield self._ordered_uids[uid_offset + start : uid_offset + end], np.asarray(
                    array[start:end], dtype=np.float32
                )
            uid_offset += array.shape[0]

    @staticmethod
    def _load_manifest(path: Path) -> dict[str, Any]:
        if not path.is_file():
            raise FileNotFoundError(f"Embedding manifest does not exist: {path}")
        try:
            manifest = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise FeatureStoreValidationError(f"Invalid embedding manifest {path}: {error}") from error
        required = {"schema_version", "encoder", "storage_dtype", "normalized", "embedding_dimension", "count", "source", "shards"}
        missing = sorted(required - manifest.keys()) if isinstance(manifest, dict) else required
        if missing or manifest.get("schema_version") != "1.0":
            raise FeatureStoreValidationError(
                f"Embedding manifest is missing required fields or schema is unsupported: {missing}"
            )
        if manifest["normalized"] is not True or manifest["embedding_dimension"] is None:
            raise FeatureStoreValidationError("Embedding manifest must describe normalized, dimensioned vectors")
        source = manifest["source"]
        uids = source.get("keyframe_uid_order") if isinstance(source, dict) else None
        if not isinstance(uids, list) or not all(isinstance(uid, str) and uid for uid in uids):
            raise FeatureMappingVerificationError("Embedding manifest has no valid source keyframe UID order")
        expected_hash = hashlib.sha256(
            json.dumps(uids, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()
        if source.get("keyframe_uid_order_sha256") != expected_hash:
            raise FeatureMappingVerificationError("Embedding manifest keyframe UID order checksum is invalid")
        return manifest

    def _validate_metadata(self, keyframes: Sequence[KeyframeRecord]) -> dict[str, KeyframeRecord]:
        records = {record.keyframe_uid: record for record in keyframes}
        if len(records) != len(keyframes):
            raise FeatureMappingVerificationError("Keyframe metadata has duplicate UIDs")
        if len(set(self._ordered_uids)) != len(self._ordered_uids):
            raise FeatureMappingVerificationError("Embedding manifest has duplicate keyframe UIDs")
        missing = sorted(set(self._ordered_uids) - set(records))
        if missing:
            raise FeatureMappingVerificationError(
                "Embedding rows reference missing keyframes: " + ", ".join(missing[:10])
            )
        mapped = {uid: records[uid] for uid in self._ordered_uids}
        incomplete = [
            uid
            for uid, record in mapped.items()
            if not record.has_mapping or record.original_frame_id is None or record.timestamp_sec is None
        ]
        if incomplete:
            raise FeatureMappingVerificationError(
                "Embedding retrieval requires video/frame/timestamp mapping: " + ", ".join(incomplete[:10])
            )
        return mapped

    def _load_shards(self, mmap: bool) -> tuple[np.ndarray, ...]:
        arrays: list[np.ndarray] = []
        expected_start = 0
        for index, shard in enumerate(self._manifest["shards"]):
            start = shard.get("row_start")
            end = shard.get("row_end")
            uids = shard.get("keyframe_uids")
            if start != expected_start or not isinstance(end, int) or end <= start:
                raise FeatureStoreValidationError(f"Embedding shard {index} has invalid row range")
            if uids != list(self._ordered_uids[start:end]):
                raise FeatureMappingVerificationError(f"Embedding shard {index} UID mapping does not match source order")
            path = self._manifest_path.parent / str(shard.get("file", ""))
            metadata_path = self._manifest_path.parent / str(shard.get("metadata_file", ""))
            if not path.is_file() or not metadata_path.is_file():
                raise FileNotFoundError(f"Embedding shard or metadata does not exist: {path}")
            if shard.get("sha256") != self._sha256_file(path):
                raise FeatureStoreValidationError(f"Embedding shard {index} checksum does not match manifest")
            try:
                array = np.load(path, mmap_mode="r" if mmap else None, allow_pickle=False)
                metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
            except (OSError, ValueError) as error:
                raise FeatureStoreValidationError(f"Cannot load embedding shard {path}: {error}") from error
            except json.JSONDecodeError as error:
                raise FeatureStoreValidationError(f"Cannot load embedding shard metadata {metadata_path}: {error}") from error
            if not isinstance(array, np.ndarray) or array.ndim != 2:
                raise FeatureStoreValidationError(f"Embedding shard {index} is not a two-dimensional .npy matrix")
            if array.shape != (end - start, self.dimension):
                raise FeatureStoreValidationError(f"Embedding shard {index} shape does not match manifest")
            if str(array.dtype) != self._manifest["storage_dtype"]:
                raise FeatureStoreValidationError(f"Embedding shard {index} dtype does not match manifest")
            if metadata.get("keyframe_uids") != uids or metadata.get("sha256") != shard.get("sha256"):
                raise FeatureMappingVerificationError(f"Embedding shard {index} metadata does not match manifest")
            arrays.append(array)
            expected_start = end
        if expected_start != self.count or self._manifest["count"] != self.count:
            raise FeatureStoreValidationError("Embedding manifest shard rows do not match total count")
        return tuple(arrays)

    def _validate_vectors(self, batch_size: int, mmap: bool) -> FeatureValidationReport:
        nan_count = 0
        inf_count = 0
        zero_vector_count = 0
        min_norm = math.inf
        max_norm = 0.0
        for _, vectors in self.iter_batches(batch_size):
            nan_count += int(np.isnan(vectors).sum())
            inf_count += int(np.isinf(vectors).sum())
            if not np.isfinite(vectors).all():
                continue
            norms = np.linalg.norm(vectors, axis=1)
            zero_vector_count += int(np.count_nonzero(norms == 0))
            if norms.size:
                min_norm = min(min_norm, float(norms.min()))
                max_norm = max(max_norm, float(norms.max()))
        if nan_count or inf_count or zero_vector_count:
            raise FeatureStoreValidationError(
                f"Embedding vectors are invalid: NaN={nan_count}, Inf={inf_count}, zero={zero_vector_count}"
            )
        return FeatureValidationReport(
            count=self.count,
            dimension=self.dimension,
            dtypes=tuple(sorted({str(array.dtype) for array in self._arrays})),
            nan_count=nan_count,
            inf_count=inf_count,
            zero_vector_count=zero_vector_count,
            min_norm=min_norm,
            max_norm=max_norm,
            vectors_are_l2_normalized=bool(abs(min_norm - 1.0) < 1e-3 and abs(max_norm - 1.0) < 1e-3),
            uses_mmap=mmap,
        )

    @staticmethod
    def _sha256_file(path: Path) -> str:
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()
